/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cliente;
import dominio.NombreCompleto;
import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import interfaces.INombresCompletosDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Encriptador;

/**
 *
 * @author Oscar
 */
public class IniciarSesion extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(RegistrarCliente.class.getName());
    private final IClientesDAO clientesDAO;
    private final INombresCompletosDAO nombresCompletosDAO;
    
    /**
     * Creates new form IniciarSesion
     * @param clientesDAO
     * @param nombresCompletosDAO
     */
    public IniciarSesion(IClientesDAO clientesDAO, INombresCompletosDAO nombresCompletosDAO) {
        this.clientesDAO = clientesDAO;
        this.nombresCompletosDAO = nombresCompletosDAO;
        initComponents();
    }

    private void mostrarMensajeClienteIniciaSesion(Cliente cliente){
        JOptionPane.showConfirmDialog(this, "!Bienvenido " + cliente.getUsuario()+ "!", "Éxito", JOptionPane.DEFAULT_OPTION);
    }
    
    private void mostrarErrorAlNoPoderIniciarSesion(String msg){
        JOptionPane.showMessageDialog(this, "Credenciales invalidas.\n" + msg, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloIniciarSesion = new javax.swing.JLabel();
        tituloUsuario = new javax.swing.JLabel();
        txtIniciarSesion = new javax.swing.JTextField();
        tituloContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tituloIniciarSesion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloIniciarSesion.setText("Iniciar sesión");

        tituloUsuario.setText("Usuario:");

        txtIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIniciarSesionActionPerformed(evt);
            }
        });

        tituloContrasenia.setText("Contraseña:");

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tituloIniciarSesion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloUsuario)
                        .addGap(6, 6, 6)
                        .addComponent(txtIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloContrasenia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciarSesion)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloIniciarSesion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloUsuario)
                    .addComponent(txtIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIniciarSesionActionPerformed
        
    }//GEN-LAST:event_txtIniciarSesionActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String usuario = this.txtIniciarSesion.getText();
        char[] arr = this.txtContrasenia.getPassword();
        String contrasenia = Encriptador.encriptar(new String(arr));
        
        Cliente cliente = null;
        NombreCompleto nombre = null;
        
        PantallaPrincipal inicio = null;
        
        try {
            cliente = this.clientesDAO.consultarPorUsuario(usuario);
        } catch (PersistenciaException ex) {
            Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            nombre = this.nombresCompletosDAO.consultar(cliente.getIdCliente());
        } catch (PersistenciaException ex) {
            Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (cliente == null) {
            this.mostrarErrorAlNoPoderIniciarSesion("Usuario o contraseña incorrectas.");
        } else if (cliente.getContrasenia().equals(contrasenia) && nombre != null) {
            try {
                inicio = new PantallaPrincipal(cliente.getIdCliente(), this.clientesDAO, this.nombresCompletosDAO);
            } catch (PersistenciaException ex) {
                Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
            }
            inicio.setVisible(true);
            this.setVisible(false);
        } else {
            this.mostrarErrorAlNoPoderIniciarSesion("Usuario o contraseña incorrectas.");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel tituloContrasenia;
    private javax.swing.JLabel tituloIniciarSesion;
    private javax.swing.JLabel tituloUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
