/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dominio.Cliente;
import dominio.Direccion;
import dominio.NombreCompleto;
import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import interfaces.ICuentasDAO;
import interfaces.IDireccionesDAO;
import interfaces.INombresCompletosDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Cliente cliente;
    private NombreCompleto nombreCompleto;
    private Direccion direccion;
    private final IClientesDAO clientesDAO;
    private final INombresCompletosDAO nombresCompletosDAO = null;
    private final IDireccionesDAO direccionesDAO = null;
    private final ICuentasDAO cuentasDAO;
    
    public PantallaPrincipal(Integer idCliente, IClientesDAO clientesDAO, INombresCompletosDAO nombresCompletosDAO, ICuentasDAO cuentasDAO) throws PersistenciaException {
        this.clientesDAO = clientesDAO;
        this.cliente = clientesDAO.consultar(idCliente);
        this.nombreCompleto = nombresCompletosDAO.consultar(this.cliente.getIdNombre());
        this.cuentasDAO = cuentasDAO;
        initComponents();
    }
    
    private void mostrarMensajeDeServicio() {
        JOptionPane.showConfirmDialog(this, "Lo sentimos :(\nEstamos trabajando para usted.\nGracias por su comprensión.", "Éxito", JOptionPane.DEFAULT_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloNombreCliente = new javax.swing.JLabel();
        tituloBienvenida = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnPaginaRetirosSinCuenta = new javax.swing.JButton();
        btnPaginaTransferencias = new javax.swing.JButton();
        btnAgregarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tituloNombreCliente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloNombreCliente.setText(this.nombreCompleto.getNombres() + " " + this.nombreCompleto.getApellidoPaterno());

        tituloBienvenida.setText("¡Bienvenido de vuelta!");

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnTransferencia.setText("Transferencia");
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });

        btnRetiroSinCuenta.setText("Retiro sin cuenta");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Folio", "Fecha y hora", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnPaginaRetirosSinCuenta.setText("Retiros sin cuenta");
        btnPaginaRetirosSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaRetirosSinCuentaActionPerformed(evt);
            }
        });

        btnPaginaTransferencias.setText("Transferencias");
        btnPaginaTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaTransferenciasActionPerformed(evt);
            }
        });

        btnAgregarCuenta.setText("Añadir otra cuenta");
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAgregarCuenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(tituloBienvenida)
                                .addComponent(tituloNombreCliente)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnTransferencia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRetiroSinCuenta)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCerrarSesion))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPaginaTransferencias)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPaginaRetirosSinCuenta)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrarSesion)
                            .addComponent(tituloBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarCuenta)))
                .addGap(35, 35, 35)
                .addComponent(tituloNombreCliente)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferencia)
                    .addComponent(btnRetiroSinCuenta))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaginaRetirosSinCuenta)
                    .addComponent(btnPaginaTransferencias))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        PantallaTransferencia transferencia = null;
        try {
            transferencia = new PantallaTransferencia(cuentasDAO, cliente);
        } catch (PersistenciaException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        transferencia.setVisible(true);
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        this.mostrarMensajeDeServicio();
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        this.mostrarMensajeDeServicio();
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    private void btnPaginaTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaTransferenciasActionPerformed
        this.mostrarMensajeDeServicio();
    }//GEN-LAST:event_btnPaginaTransferenciasActionPerformed

    private void btnPaginaRetirosSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaRetirosSinCuentaActionPerformed
        this.mostrarMensajeDeServicio();
    }//GEN-LAST:event_btnPaginaRetirosSinCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPaginaRetirosSinCuenta;
    private javax.swing.JButton btnPaginaTransferencias;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tituloBienvenida;
    private javax.swing.JLabel tituloNombreCliente;
    // End of variables declaration//GEN-END:variables
}
